import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import {randomUUID} from 'node:crypto'; import {z} from 'zod'; import db from './db.js'; import {orchestrate} from './agents.js';
const app=express(),port=process.env.PORT||4000,secret=process.env.JWT_SECRET||'dev-only-change-this-secret';
app.use(cors({origin:process.env.CLIENT_ORIGIN||true}));app.use(express.json({limit:'1mb'}));
const authSchema=z.object({name:z.string().min(2).max(60).optional(),email:z.string().email().max(120),password:z.string().min(8).max(100)});
const requestSchema=z.object({title:z.string().min(4).max(100),category:z.enum(['Customer Support','Finance','IT & Access','Operations']),requester:z.string().min(2).max(80),description:z.string().min(12).max(1200),priority:z.enum(['Normal','High'])});
function protect(req,res,next){try{const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');req.user=jwt.verify(token,secret);next()}catch{return res.status(401).json({error:'Please sign in to continue.'})}}
app.get('/api/health',(_,res)=>res.json({ok:true,aiConfigured:Boolean(process.env.GEMINI_API_KEY)}));
app.post('/api/auth/register',async(req,res)=>{const v=authSchema.safeParse(req.body);if(!v.success)return res.status(400).json({error:v.error.issues[0].message});const {email,password,name}=v.data;try{const hash=await bcrypt.hash(password,10);const info=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name||email.split('@')[0],email.toLowerCase(),hash);const user={id:info.lastInsertRowid,name:name||email.split('@')[0],email:email.toLowerCase()};res.status(201).json({token:jwt.sign(user,secret,{expiresIn:'12h'}),user})}catch{res.status(409).json({error:'An account with this email already exists.'})}});
app.post('/api/auth/login',async(req,res)=>{const v=authSchema.pick({email:true,password:true}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Enter a valid email and password.'});const row=db.prepare('SELECT * FROM users WHERE email=?').get(v.data.email.toLowerCase());if(!row||!await bcrypt.compare(v.data.password,row.password_hash))return res.status(401).json({error:'Email or password is incorrect.'});const user={id:row.id,name:row.name,email:row.email};res.json({token:jwt.sign(user,secret,{expiresIn:'12h'}),user})});
app.get('/api/requests',protect,(req,res)=>{const rows=db.prepare('SELECT * FROM requests ORDER BY created_at DESC').all();res.json(rows.map(row=>({...row,plan:JSON.parse(row.plan)})))});
app.post('/api/requests',protect,async(req,res)=>{const v=requestSchema.safeParse(req.body);if(!v.success)return res.status(400).json({error:v.error.issues[0].message});const plan=await orchestrate(v.data),id=randomUUID(),created_at=new Date().toISOString();db.prepare('INSERT INTO requests(id,title,category,requester,description,priority,status,created_at,plan,risk,outcome) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,v.data.title,v.data.category,v.data.requester,v.data.description,plan.priority,'Needs review',created_at,JSON.stringify(plan),plan.risk,plan.recommendation);res.status(201).json({id,...v.data,priority:plan.priority,status:'Needs review',created_at,plan,risk:plan.risk,outcome:plan.recommendation})});
app.patch('/api/requests/:id/status',protect,(req,res)=>{const v=z.object({status:z.enum(['Needs review','Approved','In progress','Resolved'])}).safeParse(req.body);if(!v.success)return res.status(400).json({error:'Choose a valid status.'});const result=db.prepare('UPDATE requests SET status=? WHERE id=?').run(v.data.status,req.params.id);if(!result.changes)return res.status(404).json({error:'Request not found.'});res.json({ok:true,status:v.data.status})});
app.get('/api/requests/:id',protect,(req,res)=>{const row=db.prepare('SELECT * FROM requests WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Request not found.'});res.json({...row,plan:JSON.parse(row.plan)})});
if(process.env.NODE_ENV==='production'){const path=await import('node:path');const {fileURLToPath}=await import('node:url');const root=path.dirname(fileURLToPath(import.meta.url));app.use(express.static(path.join(root,'../dist')));app.get('*',(_,res)=>res.sendFile(path.join(root,'../dist/index.html')))}
app.listen(port,()=>console.log(`RelayOps API listening on ${port}`));
